name= "pastebin-worker"
compatibility_date = "2023-11-28"
account_id= "a7bf4aeefe6f6429350a8dd160d952e2"
main = "src/index.ts"
workers_dev = false

vars = { ENVIRONMENT = "production" }
route = { pattern = "note.521986.xyz", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "9076451442be42bb802c1dee2aa4fed6" },
  { binding = "PBIMGS", id ="25abc4dbcfe74f62976ef81d2c8fbfae" }
]

[site]
bucket = "./static/dist"
